---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/alvarolop/keycloak-playground.git
    targetRevision: main
    path: keycloak-chart
    helm:
      values: |
        global:
          clusterDomain: $CLUSTER_DOMAIN
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
