{{- range $realm := .Values.realms }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: {{ $realm.name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  keycloakCRName: keycloak
  realm:
    id: {{ $realm.name }}
    realm: {{ $realm.name }}
    displayName: {{ $realm.displayName }}
    enabled: true
    clients:
      {{- range $client := $realm.clients }}
      - name: {{ $client.name }}
        clientId: {{ $client.name }}
        enabled: true
        redirectUris:
          - "https://oauth-openshift.apps.{{ $.Values.global.clusterDomain }}/oauth2callback/keycloak/*"
          - "http://localhost:8080/*"
        webOrigins:
          - "+"
        directAccessGrantsEnabled: true
        standardFlowEnabled: true
        serviceAccountsEnabled: true
        clientAuthenticatorType: client-secret
        secret: {{ $client.name }}-secret
        authorizationServicesEnabled: true
        protocol: openid-connect
        publicClient: false
        attributes:
          access.token.lifespan: "300"
      {{- end }}
    roles:
      realm:
        {{- range $role := $realm.roles }}
        - name: {{ $role.name }}
          description: {{ $role.description }}
        {{- end }}
    users:
      {{- range $user := $realm.users }}
      - username: {{ $user.username }}
        # https://github.com/keycloak/keycloak/issues/43195
        createdTimestamp: {{ $user.createdTimestamp }}
        email: {{ $user.email }}
        emailVerified: {{ $user.emailVerified }}
        firstName: {{ $user.firstName }}
        lastName: {{ $user.lastName }}
        enabled: {{ $user.enabled }}
        credentials:
          - type: password
            value: {{ $user.password }}
        realmRoles:
          {{- range $role := $user.realmRoles }}
          - {{ $role }}
          {{- end }}
        groups:
          {{- range $group := $user.groups }}
          - {{ $group }}
          {{- end }}
      {{- end }}
    groups:
      {{- range $group := $realm.groups }}
      - name: {{ $group.name }}
        displayName: {{ $group.displayName }}
        subGroups:
          {{- range $subGroup := $group.subGroups }}
          - name: {{ $subGroup.name }}
            displayName: {{ $subGroup.displayName }}
          {{- end }}
      {{- end }}
{{- end }}
